# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Reopened'), (3, 'Resolved'), (4, 'Closed'), (5, 'Duplicate')], default=1, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
